[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/twelve_factor_python_core"]

[project]
name = "twelve-factor-python-core"
version = "0.1.0"
dependencies = [
    "fastapi[standard]",
    "psycopg2"
]
